services:
  redis:
    image: redis:7-alpine
    container_name: inventory_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  db:
    image: postgres:16-alpine
    container_name: inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 3s
      retries: 20
  rabbitmq:
    image: rabbitmq:3-management
    container_name: inventory_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
  worker:
    build:
      context: .
    command: node src/worker/orderConsumer.js
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env.docker
    restart: unless-stopped
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - /home/badru/apps/monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - lokidata:/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /home/badru/apps/monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    restart: unless-stopped
  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  lokidata:
  grafanadata: